# Generated by Django 4.1.7 on 2023-03-31 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80)),
                ("category", models.CharField(max_length=20)),
                ("company", models.CharField(max_length=50)),
                ("url", models.URLField(max_length=120)),
            ],
        ),
    ]
